// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Parkking.Infrastructure.Persistence;

#nullable disable

namespace Parkking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EstacionamientoContext))]
    [Migration("20260611191642_mod-security")]
    partial class modsecurity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccionGrupo", b =>
                {
                    b.Property<int>("AccionesACC_ID")
                        .HasColumnType("integer");

                    b.Property<int>("GruposGRU_ID")
                        .HasColumnType("integer");

                    b.HasKey("AccionesACC_ID", "GruposGRU_ID");

                    b.HasIndex("GruposGRU_ID");

                    b.ToTable("AccionGrupo");
                });

            modelBuilder.Entity("CocheraTipoVehiculo", b =>
                {
                    b.Property<int>("CocherasCocheraId")
                        .HasColumnType("integer");

                    b.Property<int>("VehiculosPermitidosTipoVehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("CocherasCocheraId", "VehiculosPermitidosTipoVehiculoId");

                    b.HasIndex("VehiculosPermitidosTipoVehiculoId");

                    b.ToTable("CocheraTipoVehiculo");
                });

            modelBuilder.Entity("Parkking.Models.AbonoCochera", b =>
                {
                    b.Property<int>("AbonoCocheraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AbonoCocheraId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Cobrador")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CocheraId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioCobro")
                        .HasColumnType("date");

                    b.Property<string>("ModeloVehiculo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Patente")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("PrecioAcordado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoVehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("AbonoCocheraId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CocheraId");

                    b.HasIndex("TipoVehiculoId");

                    b.ToTable("AbonoCocheras");
                });

            modelBuilder.Entity("Parkking.Models.CajaMensual", b =>
                {
                    b.Property<int>("CajaMensualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CajaMensualId"));

                    b.Property<bool>("Cerrada")
                        .HasColumnType("boolean");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Mes")
                        .HasColumnType("date");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalGastos")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalIngresos")
                        .HasColumnType("numeric");

                    b.HasKey("CajaMensualId");

                    b.HasIndex("EstacionamientoId");

                    b.ToTable("CajasMensuales");
                });

            modelBuilder.Entity("Parkking.Models.CategoriaCochera", b =>
                {
                    b.Property<int>("CategoriaCocheraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoriaCocheraId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoriaCocheraId");

                    b.HasIndex("EstacionamientoId");

                    b.ToTable("CategoriasCochera");
                });

            modelBuilder.Entity("Parkking.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClienteId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ClienteId");

                    b.HasIndex("EstacionamientoId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Parkking.Models.Cochera", b =>
                {
                    b.Property<int>("CocheraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CocheraId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoriaCocheraId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoCochera")
                        .HasColumnType("integer");

                    b.Property<bool>("MultipleOcupacion")
                        .HasColumnType("boolean");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.HasKey("CocheraId");

                    b.HasIndex("CategoriaCocheraId");

                    b.HasIndex("EstacionamientoId");

                    b.ToTable("Cocheras");
                });

            modelBuilder.Entity("Parkking.Models.Estacionamiento", b =>
                {
                    b.Property<int>("EstacionamientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EstacionamientoId"));

                    b.Property<bool>("AplicaRecargo")
                        .HasColumnType("boolean");

                    b.Property<int>("DiaVencimientoAbono")
                        .HasColumnType("integer");

                    b.Property<int?>("DiasUmbralProporcional")
                        .HasColumnType("integer");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PorcentajeRecargo")
                        .HasColumnType("numeric");

                    b.HasKey("EstacionamientoId");

                    b.ToTable("Estacionamientos");
                });

            modelBuilder.Entity("Parkking.Models.MovimientoCaja", b =>
                {
                    b.Property<int>("MovimientoCajaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovimientoCajaId"));

                    b.Property<int?>("AbonoCocheraId")
                        .HasColumnType("integer");

                    b.Property<int>("CajaMensualId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PagoMensualId")
                        .HasColumnType("integer");

                    b.Property<string>("Responsable")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("SaldoAnterior")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoPosterior")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("TipoConcepto")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("integer");

                    b.HasKey("MovimientoCajaId");

                    b.HasIndex("AbonoCocheraId");

                    b.HasIndex("CajaMensualId");

                    b.HasIndex("PagoMensualId");

                    b.ToTable("MovimientosCaja");
                });

            modelBuilder.Entity("Parkking.Models.PagoMensual", b =>
                {
                    b.Property<int>("PagoMensualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PagoMensualId"));

                    b.Property<int>("AbonoCocheraId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHoraCarga")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MercadoPagoId")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Mes")
                        .HasColumnType("date");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("Recargo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PagoMensualId");

                    b.HasIndex("AbonoCocheraId");

                    b.ToTable("PagosMensuales");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Accion", b =>
                {
                    b.Property<int>("ACC_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ACC_ID"));

                    b.Property<string>("ACC_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int?>("FOR_ID")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEstacionamientoESTACIONAMIENTO_ID")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEstacionamientoUSU_ID")
                        .HasColumnType("integer");

                    b.HasKey("ACC_ID");

                    b.HasIndex("FOR_ID");

                    b.HasIndex("UsuarioEstacionamientoUSU_ID", "UsuarioEstacionamientoESTACIONAMIENTO_ID");

                    b.ToTable("Acciones");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Estado_Grupo", b =>
                {
                    b.Property<int>("EST_GRU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EST_GRU_ID"));

                    b.Property<string>("EST_GRU_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("EST_GRU_ID");

                    b.ToTable("Estados_Grupos");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Estado_Usuario", b =>
                {
                    b.Property<int>("EST_USU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EST_USU_ID"));

                    b.Property<string>("EST_USU_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("EST_USU_ID");

                    b.ToTable("Estado_Usuario");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Formulario", b =>
                {
                    b.Property<int>("FOR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FOR_ID"));

                    b.Property<string>("FOR_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int?>("MOD_ID")
                        .HasColumnType("integer");

                    b.HasKey("FOR_ID");

                    b.HasIndex("MOD_ID");

                    b.ToTable("Formularios");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Grupo", b =>
                {
                    b.Property<int>("GRU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GRU_ID"));

                    b.Property<int>("EST_GRU_ID")
                        .HasColumnType("integer");

                    b.Property<string>("GRU_DESCRIPCION")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("GRU_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int?>("UsuarioEstacionamientoESTACIONAMIENTO_ID")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEstacionamientoUSU_ID")
                        .HasColumnType("integer");

                    b.HasKey("GRU_ID");

                    b.HasIndex("EST_GRU_ID");

                    b.HasIndex("UsuarioEstacionamientoUSU_ID", "UsuarioEstacionamientoESTACIONAMIENTO_ID");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Modulo", b =>
                {
                    b.Property<int>("MOD_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MOD_ID"));

                    b.Property<string>("MOD_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("MOD_ID");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Usuario", b =>
                {
                    b.Property<int>("USU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("USU_ID"));

                    b.Property<int?>("AccionACC_ID")
                        .HasColumnType("integer");

                    b.Property<int?>("EST_USU_ID")
                        .HasColumnType("integer");

                    b.Property<int?>("GrupoGRU_ID")
                        .HasColumnType("integer");

                    b.Property<string>("USU_CLAVE")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("USU_MAIL")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("USU_USUARIO")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("USU_ID");

                    b.HasIndex("AccionACC_ID");

                    b.HasIndex("EST_USU_ID");

                    b.HasIndex("GrupoGRU_ID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Parkking.Models.TarifaMensual", b =>
                {
                    b.Property<int>("TarifaMensualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TarifaMensualId"));

                    b.Property<int>("CategoriaCocheraId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHoraActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoVehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("TarifaMensualId");

                    b.HasIndex("CategoriaCocheraId");

                    b.HasIndex("EstacionamientoId");

                    b.HasIndex("TipoVehiculoId");

                    b.ToTable("TarifasMensuales");
                });

            modelBuilder.Entity("Parkking.Models.TipoVehiculo", b =>
                {
                    b.Property<int>("TipoVehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoVehiculoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TipoVehiculoId");

                    b.HasIndex("EstacionamientoId");

                    b.ToTable("TiposVehiculo");
                });

            modelBuilder.Entity("Parkking.Models.UsuarioEstacionamiento", b =>
                {
                    b.Property<int>("USU_ID")
                        .HasColumnType("integer");

                    b.Property<int>("ESTACIONAMIENTO_ID")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("USU_ID", "ESTACIONAMIENTO_ID");

                    b.HasIndex("EstacionamientoId");

                    b.ToTable("UsuarioEstacionamientos");
                });

            modelBuilder.Entity("AccionGrupo", b =>
                {
                    b.HasOne("Parkking.Models.Seguridad.Accion", null)
                        .WithMany()
                        .HasForeignKey("AccionesACC_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.Seguridad.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GruposGRU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CocheraTipoVehiculo", b =>
                {
                    b.HasOne("Parkking.Models.Cochera", null)
                        .WithMany()
                        .HasForeignKey("CocherasCocheraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.TipoVehiculo", null)
                        .WithMany()
                        .HasForeignKey("VehiculosPermitidosTipoVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Parkking.Models.AbonoCochera", b =>
                {
                    b.HasOne("Parkking.Models.Cliente", "Cliente")
                        .WithMany("Abonos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.Cochera", "Cochera")
                        .WithMany("Abonos")
                        .HasForeignKey("CocheraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.TipoVehiculo", "TipoVehiculo")
                        .WithMany()
                        .HasForeignKey("TipoVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Cochera");

                    b.Navigation("TipoVehiculo");
                });

            modelBuilder.Entity("Parkking.Models.CajaMensual", b =>
                {
                    b.HasOne("Parkking.Models.Estacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamiento");
                });

            modelBuilder.Entity("Parkking.Models.CategoriaCochera", b =>
                {
                    b.HasOne("Parkking.Models.Estacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamiento");
                });

            modelBuilder.Entity("Parkking.Models.Cliente", b =>
                {
                    b.HasOne("Parkking.Models.Estacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamiento");
                });

            modelBuilder.Entity("Parkking.Models.Cochera", b =>
                {
                    b.HasOne("Parkking.Models.CategoriaCochera", "CategoriaCochera")
                        .WithMany()
                        .HasForeignKey("CategoriaCocheraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaCochera");
                });

            modelBuilder.Entity("Parkking.Models.MovimientoCaja", b =>
                {
                    b.HasOne("Parkking.Models.AbonoCochera", "Abono")
                        .WithMany()
                        .HasForeignKey("AbonoCocheraId");

                    b.HasOne("Parkking.Models.CajaMensual", "CajaMensual")
                        .WithMany("Movimientos")
                        .HasForeignKey("CajaMensualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.PagoMensual", "PagoMensual")
                        .WithMany("Movimientos")
                        .HasForeignKey("PagoMensualId");

                    b.Navigation("Abono");

                    b.Navigation("CajaMensual");

                    b.Navigation("PagoMensual");
                });

            modelBuilder.Entity("Parkking.Models.PagoMensual", b =>
                {
                    b.HasOne("Parkking.Models.AbonoCochera", "AbonoCochera")
                        .WithMany("PagosMensuales")
                        .HasForeignKey("AbonoCocheraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbonoCochera");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Accion", b =>
                {
                    b.HasOne("Parkking.Models.Seguridad.Formulario", "Formulario")
                        .WithMany("Acciones")
                        .HasForeignKey("FOR_ID");

                    b.HasOne("Parkking.Models.UsuarioEstacionamiento", null)
                        .WithMany("Acciones")
                        .HasForeignKey("UsuarioEstacionamientoUSU_ID", "UsuarioEstacionamientoESTACIONAMIENTO_ID");

                    b.Navigation("Formulario");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Formulario", b =>
                {
                    b.HasOne("Parkking.Models.Seguridad.Modulo", "Modulo")
                        .WithMany("Formularios")
                        .HasForeignKey("MOD_ID");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Grupo", b =>
                {
                    b.HasOne("Parkking.Models.Seguridad.Estado_Grupo", "Estado_Grupo")
                        .WithMany()
                        .HasForeignKey("EST_GRU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.UsuarioEstacionamiento", null)
                        .WithMany("Grupos")
                        .HasForeignKey("UsuarioEstacionamientoUSU_ID", "UsuarioEstacionamientoESTACIONAMIENTO_ID");

                    b.Navigation("Estado_Grupo");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Usuario", b =>
                {
                    b.HasOne("Parkking.Models.Seguridad.Accion", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("AccionACC_ID");

                    b.HasOne("Parkking.Models.Seguridad.Estado_Usuario", "Estado_Usuario")
                        .WithMany()
                        .HasForeignKey("EST_USU_ID");

                    b.HasOne("Parkking.Models.Seguridad.Grupo", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("GrupoGRU_ID");

                    b.Navigation("Estado_Usuario");
                });

            modelBuilder.Entity("Parkking.Models.TarifaMensual", b =>
                {
                    b.HasOne("Parkking.Models.CategoriaCochera", "CategoriaCochera")
                        .WithMany()
                        .HasForeignKey("CategoriaCocheraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.Estacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.TipoVehiculo", "TipoVehiculo")
                        .WithMany()
                        .HasForeignKey("TipoVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaCochera");

                    b.Navigation("Estacionamiento");

                    b.Navigation("TipoVehiculo");
                });

            modelBuilder.Entity("Parkking.Models.TipoVehiculo", b =>
                {
                    b.HasOne("Parkking.Models.Estacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamiento");
                });

            modelBuilder.Entity("Parkking.Models.UsuarioEstacionamiento", b =>
                {
                    b.HasOne("Parkking.Models.Estacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.Seguridad.Usuario", "Usuario")
                        .WithMany("UsuarioEstacionamientos")
                        .HasForeignKey("USU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamiento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Parkking.Models.AbonoCochera", b =>
                {
                    b.Navigation("PagosMensuales");
                });

            modelBuilder.Entity("Parkking.Models.CajaMensual", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Parkking.Models.Cliente", b =>
                {
                    b.Navigation("Abonos");
                });

            modelBuilder.Entity("Parkking.Models.Cochera", b =>
                {
                    b.Navigation("Abonos");
                });

            modelBuilder.Entity("Parkking.Models.PagoMensual", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Accion", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Formulario", b =>
                {
                    b.Navigation("Acciones");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Grupo", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Modulo", b =>
                {
                    b.Navigation("Formularios");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Usuario", b =>
                {
                    b.Navigation("UsuarioEstacionamientos");
                });

            modelBuilder.Entity("Parkking.Models.UsuarioEstacionamiento", b =>
                {
                    b.Navigation("Acciones");

                    b.Navigation("Grupos");
                });
#pragma warning restore 612, 618
        }
    }
}
