// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Parkking.Infrastructure.Persistence;

#nullable disable

namespace Parkking.Infrastructure.Data.Migrations
{
    [DbContext(typeof(EstacionamientoContext))]
    [Migration("20260908223109_CuotasPagosDetallePago")]
    partial class CuotasPagosDetallePago
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccionGrupo", b =>
                {
                    b.Property<int>("AccionesACC_ID")
                        .HasColumnType("integer");

                    b.Property<int>("GruposGRU_ID")
                        .HasColumnType("integer");

                    b.HasKey("AccionesACC_ID", "GruposGRU_ID");

                    b.HasIndex("GruposGRU_ID");

                    b.ToTable("AccionGrupo");
                });

            modelBuilder.Entity("AccionUsuarioEstacionamiento", b =>
                {
                    b.Property<int>("AccionesACC_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Usuario_EstacionamientoUSU_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Usuario_EstacionamientoESTACIONAMIENTO_ID")
                        .HasColumnType("integer");

                    b.HasKey("AccionesACC_ID", "Usuario_EstacionamientoUSU_ID", "Usuario_EstacionamientoESTACIONAMIENTO_ID");

                    b.HasIndex("Usuario_EstacionamientoUSU_ID", "Usuario_EstacionamientoESTACIONAMIENTO_ID");

                    b.ToTable("AccionUsuarioEstacionamiento");
                });

            modelBuilder.Entity("CocheraTipoVehiculo", b =>
                {
                    b.Property<int>("CocherasCocheraId")
                        .HasColumnType("integer");

                    b.Property<int>("VehiculosPermitidosTipoVehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("CocherasCocheraId", "VehiculosPermitidosTipoVehiculoId");

                    b.HasIndex("VehiculosPermitidosTipoVehiculoId");

                    b.ToTable("CocheraTipoVehiculo");
                });

            modelBuilder.Entity("GrupoUsuarioEstacionamiento", b =>
                {
                    b.Property<int>("GruposGRU_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Usuario_EstacionamientoUSU_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Usuario_EstacionamientoESTACIONAMIENTO_ID")
                        .HasColumnType("integer");

                    b.HasKey("GruposGRU_ID", "Usuario_EstacionamientoUSU_ID", "Usuario_EstacionamientoESTACIONAMIENTO_ID");

                    b.HasIndex("Usuario_EstacionamientoUSU_ID", "Usuario_EstacionamientoESTACIONAMIENTO_ID");

                    b.ToTable("GrupoUsuarioEstacionamiento");
                });

            modelBuilder.Entity("Parkking.Models.Abono", b =>
                {
                    b.Property<int>("AbonoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AbonoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Cobrador")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioCobro")
                        .HasColumnType("date");

                    b.Property<int>("PeriodicidadCobro")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PrecioAcordado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AbonoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EstacionamientoId");

                    b.ToTable("Abonos", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.AbonoPlaza", b =>
                {
                    b.Property<int>("AbonoPlazaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AbonoPlazaId"));

                    b.Property<int>("AbonoId")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CocheraId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.HasKey("AbonoPlazaId");

                    b.HasIndex("CocheraId");

                    b.HasIndex("AbonoId", "CocheraId")
                        .IsUnique();

                    b.ToTable("AbonoPlazas", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.AbonoVehiculo", b =>
                {
                    b.Property<int>("AbonoVehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AbonoVehiculoId"));

                    b.Property<int>("AbonoId")
                        .HasColumnType("integer");

                    b.Property<int?>("AbonoPlazaId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<int>("Modalidad")
                        .HasColumnType("integer");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("AbonoVehiculoId");

                    b.HasIndex("AbonoId");

                    b.HasIndex("AbonoPlazaId");

                    b.HasIndex("VehiculoId")
                        .IsUnique();

                    b.ToTable("AbonoVehiculos", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.CajaMensual", b =>
                {
                    b.Property<int>("CajaMensualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CajaMensualId"));

                    b.Property<bool>("Cerrada")
                        .HasColumnType("boolean");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Mes")
                        .HasColumnType("date");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalGastos")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalIngresos")
                        .HasColumnType("numeric");

                    b.HasKey("CajaMensualId");

                    b.HasIndex("EstacionamientoId");

                    b.ToTable("CajasMensuales");
                });

            modelBuilder.Entity("Parkking.Models.CategoriaCochera", b =>
                {
                    b.Property<int>("CategoriaCocheraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoriaCocheraId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoriaCocheraId");

                    b.HasIndex("EstacionamientoId");

                    b.ToTable("CategoriasCochera");
                });

            modelBuilder.Entity("Parkking.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClienteId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ClienteId");

                    b.HasIndex("EstacionamientoId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Parkking.Models.Cochera", b =>
                {
                    b.Property<int>("CocheraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CocheraId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoriaCocheraId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoCochera")
                        .HasColumnType("integer");

                    b.Property<bool>("MultipleOcupacion")
                        .HasColumnType("boolean");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.HasKey("CocheraId");

                    b.HasIndex("CategoriaCocheraId");

                    b.ToTable("Cocheras");
                });

            modelBuilder.Entity("Parkking.Models.Cuota", b =>
                {
                    b.Property<int>("CuotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CuotaId"));

                    b.Property<int>("AbonoId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("PeriodoFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodoInicio")
                        .HasColumnType("date");

                    b.HasKey("CuotaId");

                    b.HasIndex("AbonoId", "PeriodoInicio")
                        .IsUnique();

                    b.ToTable("Cuotas", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.DetallePago", b =>
                {
                    b.Property<int>("DetallePagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetallePagoId"));

                    b.Property<int>("CuotaId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PagoId")
                        .HasColumnType("integer");

                    b.HasKey("DetallePagoId");

                    b.HasIndex("CuotaId");

                    b.HasIndex("PagoId");

                    b.ToTable("DetallesPago", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.DatosEstacionamiento", b =>
                {
                    b.Property<int>("EstacionamientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EstacionamientoId"));

                    b.Property<bool>("AplicaRecargo")
                        .HasColumnType("boolean");

                    b.Property<int>("DiaVencimientoAbono")
                        .HasColumnType("integer");

                    b.Property<int?>("DiasUmbralProporcional")
                        .HasColumnType("integer");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PorcentajeRecargo")
                        .HasColumnType("numeric");

                    b.HasKey("EstacionamientoId");

                    b.ToTable("Estacionamientos");
                });

            modelBuilder.Entity("Parkking.Models.MovimientoCaja", b =>
                {
                    b.Property<int>("MovimientoCajaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovimientoCajaId"));

                    b.Property<int?>("AbonoId")
                        .HasColumnType("integer");

                    b.Property<int>("CajaMensualId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PagoId")
                        .HasColumnType("integer");

                    b.Property<string>("Responsable")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("SaldoAnterior")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoPosterior")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("TipoConcepto")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("MovimientoCajaId");

                    b.HasIndex("AbonoId");

                    b.HasIndex("CajaMensualId");

                    b.HasIndex("PagoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MovimientosCaja");
                });

            modelBuilder.Entity("Parkking.Models.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PagoId"));

                    b.Property<int>("AbonoId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MercadoPagoId")
                        .HasColumnType("text");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("Recargo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PagoId");

                    b.HasIndex("AbonoId");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Accion", b =>
                {
                    b.Property<int>("ACC_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ACC_ID"));

                    b.Property<string>("ACC_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("ACC_ID");

                    b.ToTable("Acciones");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Grupo", b =>
                {
                    b.Property<int>("GRU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GRU_ID"));

                    b.Property<int>("EstadoGrupo")
                        .HasColumnType("integer");

                    b.Property<string>("GRU_DESCRIPCION")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("GRU_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("GRU_ID");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Modulo", b =>
                {
                    b.Property<int>("MOD_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MOD_ID"));

                    b.Property<string>("MOD_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("MOD_ID");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Usuario", b =>
                {
                    b.Property<int>("USU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("USU_ID"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("Estado_Usuario")
                        .HasColumnType("integer");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("UsuarioName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("USU_ID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Parkking.Models.TarifaMensual", b =>
                {
                    b.Property<int>("TarifaMensualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TarifaMensualId"));

                    b.Property<int>("CategoriaCocheraId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHoraActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoVehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("TarifaMensualId");

                    b.HasIndex("CategoriaCocheraId");

                    b.HasIndex("EstacionamientoId");

                    b.HasIndex("TipoVehiculoId");

                    b.ToTable("TarifasMensuales");
                });

            modelBuilder.Entity("Parkking.Models.TipoVehiculo", b =>
                {
                    b.Property<int>("TipoVehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoVehiculoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TipoVehiculoId");

                    b.HasIndex("EstacionamientoId");

                    b.ToTable("TiposVehiculo");
                });

            modelBuilder.Entity("Parkking.Models.UsuarioEstacionamiento", b =>
                {
                    b.Property<int>("USU_ID")
                        .HasColumnType("integer");

                    b.Property<int>("ESTACIONAMIENTO_ID")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UsuarioEstacionamientoId")
                        .HasColumnType("integer");

                    b.HasKey("USU_ID", "ESTACIONAMIENTO_ID");

                    b.HasIndex("ESTACIONAMIENTO_ID");

                    b.ToTable("UsuarioEstacionamientos");
                });

            modelBuilder.Entity("Parkking.Models.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehiculoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<string>("ModeloVehiculo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("TipoVehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("VehiculoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EstacionamientoId");

                    b.HasIndex("TipoVehiculoId");

                    b.ToTable("Vehiculos", (string)null);
                });

            modelBuilder.Entity("AccionGrupo", b =>
                {
                    b.HasOne("Parkking.Models.Seguridad.Accion", null)
                        .WithMany()
                        .HasForeignKey("AccionesACC_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.Seguridad.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GruposGRU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccionUsuarioEstacionamiento", b =>
                {
                    b.HasOne("Parkking.Models.Seguridad.Accion", null)
                        .WithMany()
                        .HasForeignKey("AccionesACC_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.UsuarioEstacionamiento", null)
                        .WithMany()
                        .HasForeignKey("Usuario_EstacionamientoUSU_ID", "Usuario_EstacionamientoESTACIONAMIENTO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CocheraTipoVehiculo", b =>
                {
                    b.HasOne("Parkking.Models.Cochera", null)
                        .WithMany()
                        .HasForeignKey("CocherasCocheraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.TipoVehiculo", null)
                        .WithMany()
                        .HasForeignKey("VehiculosPermitidosTipoVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrupoUsuarioEstacionamiento", b =>
                {
                    b.HasOne("Parkking.Models.Seguridad.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GruposGRU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.UsuarioEstacionamiento", null)
                        .WithMany()
                        .HasForeignKey("Usuario_EstacionamientoUSU_ID", "Usuario_EstacionamientoESTACIONAMIENTO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Parkking.Models.Abono", b =>
                {
                    b.HasOne("Parkking.Models.Cliente", "Cliente")
                        .WithMany("Abonos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.DatosEstacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Estacionamiento");
                });

            modelBuilder.Entity("Parkking.Models.AbonoPlaza", b =>
                {
                    b.HasOne("Parkking.Models.Abono", "Abono")
                        .WithMany("Plazas")
                        .HasForeignKey("AbonoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.Cochera", "Cochera")
                        .WithMany("Plazas")
                        .HasForeignKey("CocheraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abono");

                    b.Navigation("Cochera");
                });

            modelBuilder.Entity("Parkking.Models.AbonoVehiculo", b =>
                {
                    b.HasOne("Parkking.Models.Abono", "Abono")
                        .WithMany("AbonoVehiculos")
                        .HasForeignKey("AbonoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.AbonoPlaza", "AbonoPlaza")
                        .WithMany("VehiculosFijos")
                        .HasForeignKey("AbonoPlazaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Parkking.Models.Vehiculo", "Vehiculo")
                        .WithOne("AbonoVehiculo")
                        .HasForeignKey("Parkking.Models.AbonoVehiculo", "VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abono");

                    b.Navigation("AbonoPlaza");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Parkking.Models.CajaMensual", b =>
                {
                    b.HasOne("Parkking.Models.DatosEstacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamiento");
                });

            modelBuilder.Entity("Parkking.Models.CategoriaCochera", b =>
                {
                    b.HasOne("Parkking.Models.DatosEstacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamiento");
                });

            modelBuilder.Entity("Parkking.Models.Cliente", b =>
                {
                    b.HasOne("Parkking.Models.DatosEstacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamiento");
                });

            modelBuilder.Entity("Parkking.Models.Cochera", b =>
                {
                    b.HasOne("Parkking.Models.CategoriaCochera", "CategoriaCochera")
                        .WithMany()
                        .HasForeignKey("CategoriaCocheraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaCochera");
                });

            modelBuilder.Entity("Parkking.Models.Cuota", b =>
                {
                    b.HasOne("Parkking.Models.Abono", "Abono")
                        .WithMany("Cuotas")
                        .HasForeignKey("AbonoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abono");
                });

            modelBuilder.Entity("Parkking.Models.DetallePago", b =>
                {
                    b.HasOne("Parkking.Models.Cuota", "Cuota")
                        .WithMany("DetallesPago")
                        .HasForeignKey("CuotaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parkking.Models.Pago", "Pago")
                        .WithMany("Detalles")
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuota");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("Parkking.Models.MovimientoCaja", b =>
                {
                    b.HasOne("Parkking.Models.Abono", "Abono")
                        .WithMany()
                        .HasForeignKey("AbonoId");

                    b.HasOne("Parkking.Models.CajaMensual", "CajaMensual")
                        .WithMany("Movimientos")
                        .HasForeignKey("CajaMensualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.Pago", "Pago")
                        .WithMany("Movimientos")
                        .HasForeignKey("PagoId");

                    b.HasOne("Parkking.Models.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abono");

                    b.Navigation("CajaMensual");

                    b.Navigation("Pago");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Parkking.Models.Pago", b =>
                {
                    b.HasOne("Parkking.Models.Abono", "Abono")
                        .WithMany("Pagos")
                        .HasForeignKey("AbonoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abono");
                });

            modelBuilder.Entity("Parkking.Models.TarifaMensual", b =>
                {
                    b.HasOne("Parkking.Models.CategoriaCochera", "CategoriaCochera")
                        .WithMany()
                        .HasForeignKey("CategoriaCocheraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.DatosEstacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.TipoVehiculo", "TipoVehiculo")
                        .WithMany()
                        .HasForeignKey("TipoVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaCochera");

                    b.Navigation("Estacionamiento");

                    b.Navigation("TipoVehiculo");
                });

            modelBuilder.Entity("Parkking.Models.TipoVehiculo", b =>
                {
                    b.HasOne("Parkking.Models.DatosEstacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamiento");
                });

            modelBuilder.Entity("Parkking.Models.UsuarioEstacionamiento", b =>
                {
                    b.HasOne("Parkking.Models.DatosEstacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("ESTACIONAMIENTO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.Seguridad.Usuario", "Usuario")
                        .WithMany("Usuario_Estacionamiento")
                        .HasForeignKey("USU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamiento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Parkking.Models.Vehiculo", b =>
                {
                    b.HasOne("Parkking.Models.Cliente", "Cliente")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.DatosEstacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.TipoVehiculo", "TipoVehiculo")
                        .WithMany()
                        .HasForeignKey("TipoVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Estacionamiento");

                    b.Navigation("TipoVehiculo");
                });

            modelBuilder.Entity("Parkking.Models.Abono", b =>
                {
                    b.Navigation("AbonoVehiculos");

                    b.Navigation("Cuotas");

                    b.Navigation("Pagos");

                    b.Navigation("Plazas");
                });

            modelBuilder.Entity("Parkking.Models.AbonoPlaza", b =>
                {
                    b.Navigation("VehiculosFijos");
                });

            modelBuilder.Entity("Parkking.Models.CajaMensual", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Parkking.Models.Cliente", b =>
                {
                    b.Navigation("Abonos");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("Parkking.Models.Cochera", b =>
                {
                    b.Navigation("Plazas");
                });

            modelBuilder.Entity("Parkking.Models.Cuota", b =>
                {
                    b.Navigation("DetallesPago");
                });

            modelBuilder.Entity("Parkking.Models.Pago", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Usuario", b =>
                {
                    b.Navigation("Usuario_Estacionamiento");
                });

            modelBuilder.Entity("Parkking.Models.Vehiculo", b =>
                {
                    b.Navigation("AbonoVehiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
