// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Parkking.Infrastructure.Persistence;

#nullable disable

namespace Parkking.Infrastructure.Data.Migrations
{
    [DbContext(typeof(EstacionamientoContext))]
    [Migration("20260926225120_CorregirReglaClienteDesdeAbono")]
    partial class CorregirReglaClienteDesdeAbono
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccionGrupo", b =>
                {
                    b.Property<int>("AccionesACC_ID")
                        .HasColumnType("integer");

                    b.Property<int>("GruposGRU_ID")
                        .HasColumnType("integer");

                    b.HasKey("AccionesACC_ID", "GruposGRU_ID");

                    b.HasIndex("GruposGRU_ID");

                    b.ToTable("AccionGrupo");
                });

            modelBuilder.Entity("AccionUsuarioEstacionamiento", b =>
                {
                    b.Property<int>("AccionesACC_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Usuario_EstacionamientoUSU_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Usuario_EstacionamientoESTACIONAMIENTO_ID")
                        .HasColumnType("integer");

                    b.HasKey("AccionesACC_ID", "Usuario_EstacionamientoUSU_ID", "Usuario_EstacionamientoESTACIONAMIENTO_ID");

                    b.HasIndex("Usuario_EstacionamientoUSU_ID", "Usuario_EstacionamientoESTACIONAMIENTO_ID");

                    b.ToTable("AccionUsuarioEstacionamiento");
                });

            modelBuilder.Entity("CocheraTipoVehiculo", b =>
                {
                    b.Property<int>("CocherasCocheraId")
                        .HasColumnType("integer");

                    b.Property<int>("VehiculosPermitidosTipoVehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("CocherasCocheraId", "VehiculosPermitidosTipoVehiculoId");

                    b.HasIndex("VehiculosPermitidosTipoVehiculoId");

                    b.ToTable("CocheraTipoVehiculo");
                });

            modelBuilder.Entity("GrupoUsuarioEstacionamiento", b =>
                {
                    b.Property<int>("GruposGRU_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Usuario_EstacionamientoUSU_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Usuario_EstacionamientoESTACIONAMIENTO_ID")
                        .HasColumnType("integer");

                    b.HasKey("GruposGRU_ID", "Usuario_EstacionamientoUSU_ID", "Usuario_EstacionamientoESTACIONAMIENTO_ID");

                    b.HasIndex("Usuario_EstacionamientoUSU_ID", "Usuario_EstacionamientoESTACIONAMIENTO_ID");

                    b.ToTable("GrupoUsuarioEstacionamiento");
                });

            modelBuilder.Entity("Parkking.Models.Abono", b =>
                {
                    b.Property<int>("AbonoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AbonoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Cobrador")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioCobro")
                        .HasColumnType("date");

                    b.Property<int>("PeriodicidadCobro")
                        .HasColumnType("integer");

                    b.Property<int>("PoliticaPrimerPeriodo")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PrecioAcordado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AbonoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EstacionamientoId");

                    b.ToTable("Abonos", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.AbonoPlaza", b =>
                {
                    b.Property<int>("AbonoPlazaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AbonoPlazaId"));

                    b.Property<int>("AbonoId")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CocheraId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.HasKey("AbonoPlazaId");

                    b.HasIndex("CocheraId");

                    b.HasIndex("AbonoId", "CocheraId")
                        .IsUnique();

                    b.ToTable("AbonoPlazas", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.AbonoVehiculo", b =>
                {
                    b.Property<int>("AbonoVehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AbonoVehiculoId"));

                    b.Property<int>("AbonoId")
                        .HasColumnType("integer");

                    b.Property<int?>("AbonoPlazaId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<int>("Modalidad")
                        .HasColumnType("integer");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("AbonoVehiculoId");

                    b.HasIndex("AbonoId");

                    b.HasIndex("AbonoPlazaId");

                    b.HasIndex("VehiculoId")
                        .IsUnique();

                    b.ToTable("AbonoVehiculos", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.CategoriaCochera", b =>
                {
                    b.Property<int>("CategoriaCocheraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoriaCocheraId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoriaCocheraId");

                    b.HasIndex("EstacionamientoId");

                    b.ToTable("CategoriasCochera");
                });

            modelBuilder.Entity("Parkking.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClienteId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Documento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ClienteId");

                    b.HasIndex("EstacionamientoId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Parkking.Models.Cochera", b =>
                {
                    b.Property<int>("CocheraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CocheraId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoriaCocheraId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoCochera")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxOcupacion")
                        .HasColumnType("integer");

                    b.Property<bool>("MultipleOcupacion")
                        .HasColumnType("boolean");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.HasKey("CocheraId");

                    b.HasIndex("CategoriaCocheraId");

                    b.ToTable("Cocheras");
                });

            modelBuilder.Entity("Parkking.Models.Cuota", b =>
                {
                    b.Property<int>("CuotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CuotaId"));

                    b.Property<int>("AbonoId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("PeriodoFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodoInicio")
                        .HasColumnType("date");

                    b.HasKey("CuotaId");

                    b.HasIndex("AbonoId", "PeriodoInicio")
                        .IsUnique();

                    b.ToTable("Cuotas", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.DatosEstacionamiento", b =>
                {
                    b.Property<int>("EstacionamientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EstacionamientoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<bool>("AplicaRecargo")
                        .HasColumnType("boolean");

                    b.Property<int>("ContratoPlazoMeses")
                        .HasColumnType("integer");

                    b.Property<bool>("ContratoSeguroObligatorio")
                        .HasColumnType("boolean");

                    b.Property<int>("DiaVencimientoAbono")
                        .HasColumnType("integer");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailAvisos")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EnviarReciboPorEmail")
                        .HasColumnType("boolean");

                    b.Property<bool>("GenerarContratoAlCrearAbono")
                        .HasColumnType("boolean");

                    b.Property<bool>("ImprimirReciboAlCobrar")
                        .HasColumnType("boolean");

                    b.Property<string>("LocadorDocumento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("LocadorDomicilio")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LocadorNombre")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PorcentajeRecargo")
                        .HasColumnType("numeric");

                    b.HasKey("EstacionamientoId");

                    b.ToTable("Estacionamientos", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.DetalleCuota", b =>
                {
                    b.Property<int>("DetalleCuotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetalleCuotaId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CategoriaNombre")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("CocheraId")
                        .HasColumnType("integer");

                    b.Property<string>("CocheraNumero")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CuotaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Patente")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TarifaMensualId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("TipoVehiculoNombre")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("DetalleCuotaId");

                    b.HasIndex("CocheraId");

                    b.HasIndex("CuotaId");

                    b.HasIndex("EstacionamientoId");

                    b.HasIndex("TarifaMensualId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("DetallesCuota", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.DetallePago", b =>
                {
                    b.Property<int>("DetallePagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetallePagoId"));

                    b.Property<int>("CuotaId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PagoId")
                        .HasColumnType("integer");

                    b.HasKey("DetallePagoId");

                    b.HasIndex("CuotaId");

                    b.HasIndex("PagoId");

                    b.ToTable("DetallesPago", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.Documento", b =>
                {
                    b.Property<int>("DocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentoId"));

                    b.Property<int?>("AbonoId")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("RutaRelativa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("DocumentoId");

                    b.HasIndex("AbonoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VehiculoId");

                    b.HasIndex("EstacionamientoId", "Activo", "FechaCarga");

                    b.ToTable("Documentos", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.AjusteFinanciero", b =>
                {
                    b.Property<int>("AjusteFinancieroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AjusteFinancieroId"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("MovimientoId")
                        .HasColumnType("integer");

                    b.HasKey("AjusteFinancieroId");

                    b.HasIndex("MovimientoId");

                    b.ToTable("AjustesFinancieros", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.AplicacionSaldoAFavor", b =>
                {
                    b.Property<int>("AplicacionSaldoAFavorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AplicacionSaldoAFavorId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MovimientoId")
                        .HasColumnType("integer");

                    b.HasKey("AplicacionSaldoAFavorId");

                    b.HasIndex("MovimientoId");

                    b.ToTable("AplicacionesSaldoAFavor", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.AuditoriaMovimiento", b =>
                {
                    b.Property<int>("AuditoriaMovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditoriaMovimientoId"));

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int>("MovimientoId")
                        .HasColumnType("integer");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("AuditoriaMovimientoId");

                    b.HasIndex("MovimientoId");

                    b.ToTable("AuditoriasMovimiento", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.Cargo", b =>
                {
                    b.Property<int>("CargoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CargoId"));

                    b.Property<int?>("AbonoId")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CargoId");

                    b.HasIndex("AbonoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Cargos", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.CuentaCorrienteCliente", b =>
                {
                    b.Property<int>("CuentaCorrienteClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CuentaCorrienteClienteId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CuentaCorrienteClienteId");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("CuentasCorrientesCliente", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.CuentaCorrienteEstacionamiento", b =>
                {
                    b.Property<int>("CuentaCorrienteEstacionamientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CuentaCorrienteEstacionamientoId"));

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CuentaCorrienteEstacionamientoId");

                    b.HasIndex("EstacionamientoId")
                        .IsUnique();

                    b.ToTable("CuentasCorrientesEstacionamiento", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.Gasto", b =>
                {
                    b.Property<int>("GastoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GastoId"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MovimientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TipoGastoId")
                        .HasColumnType("integer");

                    b.HasKey("GastoId");

                    b.HasIndex("MovimientoId");

                    b.HasIndex("TipoGastoId");

                    b.ToTable("Gastos", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.GrupoFinanciero", b =>
                {
                    b.Property<int>("GrupoFinancieroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GrupoFinancieroId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("GrupoFinancieroId");

                    b.HasIndex("EstacionamientoId", "Nombre");

                    b.ToTable("GruposFinancieros", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.Movimiento", b =>
                {
                    b.Property<int>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovimientoId"));

                    b.Property<int?>("AbonoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("CuentaCorrienteClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("CuentaCorrienteEstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int?>("PagoId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoGastoId")
                        .HasColumnType("integer");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("MovimientoId");

                    b.HasIndex("AbonoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CuentaCorrienteClienteId");

                    b.HasIndex("CuentaCorrienteEstacionamientoId");

                    b.HasIndex("EstacionamientoId");

                    b.HasIndex("PagoId");

                    b.HasIndex("TipoGastoId");

                    b.ToTable("Movimientos", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.MovimientoGrupoFinanciero", b =>
                {
                    b.Property<int>("MovimientoId")
                        .HasColumnType("integer");

                    b.Property<int>("GrupoFinancieroId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.HasKey("MovimientoId", "GrupoFinancieroId");

                    b.HasIndex("GrupoFinancieroId");

                    b.ToTable("MovimientosGrupoFinanciero", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.ReglaAsignacion", b =>
                {
                    b.Property<int>("ReglaAsignacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReglaAsignacionId"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("Criterio")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<int>("GrupoFinancieroId")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoGastoId")
                        .HasColumnType("integer");

                    b.HasKey("ReglaAsignacionId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("GrupoFinancieroId");

                    b.HasIndex("TipoGastoId");

                    b.ToTable("ReglasAsignacion", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.Reintegro", b =>
                {
                    b.Property<int>("ReintegroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReintegroId"));

                    b.Property<string>("Beneficiario")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Medio")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("MovimientoId")
                        .HasColumnType("integer");

                    b.HasKey("ReintegroId");

                    b.HasIndex("MovimientoId");

                    b.ToTable("Reintegros", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.TipoGasto", b =>
                {
                    b.Property<int>("TipoGastoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoGastoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("TipoGastoId");

                    b.ToTable("TiposGasto", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.Mensaje", b =>
                {
                    b.Property<int>("MensajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MensajeId"));

                    b.Property<int?>("AbonoId")
                        .HasColumnType("integer");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ReciboId")
                        .HasColumnType("integer");

                    b.Property<string>("Remitente")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("MensajeId");

                    b.HasIndex("ReciboId");

                    b.HasIndex("EstacionamientoId", "Fecha");

                    b.ToTable("Mensajes", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.MetodoDePago", b =>
                {
                    b.Property<int>("MetodoDePagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MetodoDePagoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MetodoDePagoId");

                    b.HasIndex("EstacionamientoId", "Nombre");

                    b.ToTable("MetodosDePago", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PagoId"));

                    b.Property<int>("AbonoId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MercadoPagoId")
                        .HasColumnType("text");

                    b.Property<int?>("MetodoDePagoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("Recargo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PagoId");

                    b.HasIndex("AbonoId");

                    b.HasIndex("MetodoDePagoId");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.Recibo", b =>
                {
                    b.Property<int>("ReciboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReciboId"));

                    b.Property<int>("AbonoId")
                        .HasColumnType("integer");

                    b.Property<bool>("Anulado")
                        .HasColumnType("boolean");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Cobrador")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CocherasLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MetodoPagoLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("PagoId")
                        .HasColumnType("integer");

                    b.Property<string>("PatentesLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PeriodosLabel")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Recargo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ReciboId");

                    b.HasIndex("PagoId")
                        .IsUnique();

                    b.HasIndex("EstacionamientoId", "Numero")
                        .IsUnique();

                    b.ToTable("Recibos", (string)null);
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Accion", b =>
                {
                    b.Property<int>("ACC_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ACC_ID"));

                    b.Property<string>("ACC_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("ACC_ID");

                    b.ToTable("Acciones");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Grupo", b =>
                {
                    b.Property<int>("GRU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GRU_ID"));

                    b.Property<int>("EstadoGrupo")
                        .HasColumnType("integer");

                    b.Property<string>("GRU_DESCRIPCION")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("GRU_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("GRU_ID");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Modulo", b =>
                {
                    b.Property<int>("MOD_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MOD_ID"));

                    b.Property<string>("MOD_NOMBRE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("MOD_ID");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Usuario", b =>
                {
                    b.Property<int>("USU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("USU_ID"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("Estado_Usuario")
                        .HasColumnType("integer");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("UsuarioName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("USU_ID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Parkking.Models.TarifaMensual", b =>
                {
                    b.Property<int>("TarifaMensualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TarifaMensualId"));

                    b.Property<int>("CategoriaCocheraId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHoraActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PeriodicidadCobro")
                        .HasColumnType("integer");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoVehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("TarifaMensualId");

                    b.HasIndex("CategoriaCocheraId");

                    b.HasIndex("EstacionamientoId");

                    b.HasIndex("TipoVehiculoId");

                    b.ToTable("TarifasMensuales");
                });

            modelBuilder.Entity("Parkking.Models.TipoVehiculo", b =>
                {
                    b.Property<int>("TipoVehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoVehiculoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TipoVehiculoId");

                    b.HasIndex("EstacionamientoId");

                    b.ToTable("TiposVehiculo");
                });

            modelBuilder.Entity("Parkking.Models.UsuarioEstacionamiento", b =>
                {
                    b.Property<int>("USU_ID")
                        .HasColumnType("integer");

                    b.Property<int>("ESTACIONAMIENTO_ID")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UsuarioEstacionamientoId")
                        .HasColumnType("integer");

                    b.HasKey("USU_ID", "ESTACIONAMIENTO_ID");

                    b.HasIndex("ESTACIONAMIENTO_ID");

                    b.ToTable("UsuarioEstacionamientos");
                });

            modelBuilder.Entity("Parkking.Models.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehiculoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<string>("ModeloVehiculo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("TipoVehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("VehiculoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EstacionamientoId");

                    b.HasIndex("TipoVehiculoId");

                    b.ToTable("Vehiculos", (string)null);
                });

            modelBuilder.Entity("AccionGrupo", b =>
                {
                    b.HasOne("Parkking.Models.Seguridad.Accion", null)
                        .WithMany()
                        .HasForeignKey("AccionesACC_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.Seguridad.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GruposGRU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccionUsuarioEstacionamiento", b =>
                {
                    b.HasOne("Parkking.Models.Seguridad.Accion", null)
                        .WithMany()
                        .HasForeignKey("AccionesACC_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.UsuarioEstacionamiento", null)
                        .WithMany()
                        .HasForeignKey("Usuario_EstacionamientoUSU_ID", "Usuario_EstacionamientoESTACIONAMIENTO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CocheraTipoVehiculo", b =>
                {
                    b.HasOne("Parkking.Models.Cochera", null)
                        .WithMany()
                        .HasForeignKey("CocherasCocheraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.TipoVehiculo", null)
                        .WithMany()
                        .HasForeignKey("VehiculosPermitidosTipoVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrupoUsuarioEstacionamiento", b =>
                {
                    b.HasOne("Parkking.Models.Seguridad.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GruposGRU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.UsuarioEstacionamiento", null)
                        .WithMany()
                        .HasForeignKey("Usuario_EstacionamientoUSU_ID", "Usuario_EstacionamientoESTACIONAMIENTO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Parkking.Models.Abono", b =>
                {
                    b.HasOne("Parkking.Models.Cliente", "Cliente")
                        .WithMany("Abonos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.DatosEstacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Estacionamiento");
                });

            modelBuilder.Entity("Parkking.Models.AbonoPlaza", b =>
                {
                    b.HasOne("Parkking.Models.Abono", "Abono")
                        .WithMany("Plazas")
                        .HasForeignKey("AbonoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.Cochera", "Cochera")
                        .WithMany("Plazas")
                        .HasForeignKey("CocheraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abono");

                    b.Navigation("Cochera");
                });

            modelBuilder.Entity("Parkking.Models.AbonoVehiculo", b =>
                {
                    b.HasOne("Parkking.Models.Abono", "Abono")
                        .WithMany("AbonoVehiculos")
                        .HasForeignKey("AbonoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.AbonoPlaza", "AbonoPlaza")
                        .WithMany("VehiculosFijos")
                        .HasForeignKey("AbonoPlazaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Parkking.Models.Vehiculo", "Vehiculo")
                        .WithOne("AbonoVehiculo")
                        .HasForeignKey("Parkking.Models.AbonoVehiculo", "VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abono");

                    b.Navigation("AbonoPlaza");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Parkking.Models.CategoriaCochera", b =>
                {
                    b.HasOne("Parkking.Models.DatosEstacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamiento");
                });

            modelBuilder.Entity("Parkking.Models.Cliente", b =>
                {
                    b.HasOne("Parkking.Models.DatosEstacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamiento");
                });

            modelBuilder.Entity("Parkking.Models.Cochera", b =>
                {
                    b.HasOne("Parkking.Models.CategoriaCochera", "CategoriaCochera")
                        .WithMany()
                        .HasForeignKey("CategoriaCocheraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaCochera");
                });

            modelBuilder.Entity("Parkking.Models.Cuota", b =>
                {
                    b.HasOne("Parkking.Models.Abono", "Abono")
                        .WithMany("Cuotas")
                        .HasForeignKey("AbonoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abono");
                });

            modelBuilder.Entity("Parkking.Models.DetalleCuota", b =>
                {
                    b.HasOne("Parkking.Models.Cochera", "Cochera")
                        .WithMany()
                        .HasForeignKey("CocheraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Parkking.Models.Cuota", "Cuota")
                        .WithMany("Detalles")
                        .HasForeignKey("CuotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.DatosEstacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.TarifaMensual", "Tarifa")
                        .WithMany()
                        .HasForeignKey("TarifaMensualId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Parkking.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cochera");

                    b.Navigation("Cuota");

                    b.Navigation("Estacionamiento");

                    b.Navigation("Tarifa");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Parkking.Models.DetallePago", b =>
                {
                    b.HasOne("Parkking.Models.Cuota", "Cuota")
                        .WithMany("DetallesPago")
                        .HasForeignKey("CuotaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parkking.Models.Pago", "Pago")
                        .WithMany("Detalles")
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuota");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("Parkking.Models.Documento", b =>
                {
                    b.HasOne("Parkking.Models.Abono", "Abono")
                        .WithMany()
                        .HasForeignKey("AbonoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Parkking.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Parkking.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Abono");

                    b.Navigation("Cliente");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.AjusteFinanciero", b =>
                {
                    b.HasOne("Parkking.Models.Finanzas.Movimiento", "Movimiento")
                        .WithMany()
                        .HasForeignKey("MovimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movimiento");
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.AplicacionSaldoAFavor", b =>
                {
                    b.HasOne("Parkking.Models.Finanzas.Movimiento", "Movimiento")
                        .WithMany()
                        .HasForeignKey("MovimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movimiento");
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.AuditoriaMovimiento", b =>
                {
                    b.HasOne("Parkking.Models.Finanzas.Movimiento", "Movimiento")
                        .WithMany("Auditorias")
                        .HasForeignKey("MovimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movimiento");
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.Cargo", b =>
                {
                    b.HasOne("Parkking.Models.Abono", null)
                        .WithMany()
                        .HasForeignKey("AbonoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Parkking.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.CuentaCorrienteCliente", b =>
                {
                    b.HasOne("Parkking.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.Gasto", b =>
                {
                    b.HasOne("Parkking.Models.Finanzas.Movimiento", "Movimiento")
                        .WithMany()
                        .HasForeignKey("MovimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.Finanzas.TipoGasto", "TipoGasto")
                        .WithMany("Gastos")
                        .HasForeignKey("TipoGastoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movimiento");

                    b.Navigation("TipoGasto");
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.Movimiento", b =>
                {
                    b.HasOne("Parkking.Models.Abono", "Abono")
                        .WithMany()
                        .HasForeignKey("AbonoId");

                    b.HasOne("Parkking.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("Parkking.Models.Finanzas.CuentaCorrienteCliente", "CuentaCorrienteCliente")
                        .WithMany()
                        .HasForeignKey("CuentaCorrienteClienteId");

                    b.HasOne("Parkking.Models.Finanzas.CuentaCorrienteEstacionamiento", "CuentaCorrienteEstacionamiento")
                        .WithMany()
                        .HasForeignKey("CuentaCorrienteEstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.Pago", "Pago")
                        .WithMany()
                        .HasForeignKey("PagoId");

                    b.HasOne("Parkking.Models.Finanzas.TipoGasto", "TipoGasto")
                        .WithMany()
                        .HasForeignKey("TipoGastoId");

                    b.Navigation("Abono");

                    b.Navigation("Cliente");

                    b.Navigation("CuentaCorrienteCliente");

                    b.Navigation("CuentaCorrienteEstacionamiento");

                    b.Navigation("Pago");

                    b.Navigation("TipoGasto");
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.MovimientoGrupoFinanciero", b =>
                {
                    b.HasOne("Parkking.Models.Finanzas.GrupoFinanciero", "GrupoFinanciero")
                        .WithMany("Movimientos")
                        .HasForeignKey("GrupoFinancieroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.Finanzas.Movimiento", "Movimiento")
                        .WithMany("Grupos")
                        .HasForeignKey("MovimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoFinanciero");

                    b.Navigation("Movimiento");
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.ReglaAsignacion", b =>
                {
                    b.HasOne("Parkking.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("Parkking.Models.Finanzas.GrupoFinanciero", "GrupoFinanciero")
                        .WithMany("Reglas")
                        .HasForeignKey("GrupoFinancieroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.Finanzas.TipoGasto", "TipoGasto")
                        .WithMany("Reglas")
                        .HasForeignKey("TipoGastoId");

                    b.Navigation("Cliente");

                    b.Navigation("GrupoFinanciero");

                    b.Navigation("TipoGasto");
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.Reintegro", b =>
                {
                    b.HasOne("Parkking.Models.Finanzas.Movimiento", "Movimiento")
                        .WithMany()
                        .HasForeignKey("MovimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movimiento");
                });

            modelBuilder.Entity("Parkking.Models.MetodoDePago", b =>
                {
                    b.HasOne("Parkking.Models.DatosEstacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamiento");
                });

            modelBuilder.Entity("Parkking.Models.Pago", b =>
                {
                    b.HasOne("Parkking.Models.Abono", "Abono")
                        .WithMany("Pagos")
                        .HasForeignKey("AbonoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.MetodoDePago", "MetodoDePago")
                        .WithMany()
                        .HasForeignKey("MetodoDePagoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Abono");

                    b.Navigation("MetodoDePago");
                });

            modelBuilder.Entity("Parkking.Models.Recibo", b =>
                {
                    b.HasOne("Parkking.Models.Pago", "Pago")
                        .WithOne("Recibo")
                        .HasForeignKey("Parkking.Models.Recibo", "PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("Parkking.Models.TarifaMensual", b =>
                {
                    b.HasOne("Parkking.Models.CategoriaCochera", "CategoriaCochera")
                        .WithMany()
                        .HasForeignKey("CategoriaCocheraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.DatosEstacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.TipoVehiculo", "TipoVehiculo")
                        .WithMany()
                        .HasForeignKey("TipoVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaCochera");

                    b.Navigation("Estacionamiento");

                    b.Navigation("TipoVehiculo");
                });

            modelBuilder.Entity("Parkking.Models.TipoVehiculo", b =>
                {
                    b.HasOne("Parkking.Models.DatosEstacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamiento");
                });

            modelBuilder.Entity("Parkking.Models.UsuarioEstacionamiento", b =>
                {
                    b.HasOne("Parkking.Models.DatosEstacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("ESTACIONAMIENTO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.Seguridad.Usuario", "Usuario")
                        .WithMany("Usuario_Estacionamiento")
                        .HasForeignKey("USU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamiento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Parkking.Models.Vehiculo", b =>
                {
                    b.HasOne("Parkking.Models.Cliente", "Cliente")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.DatosEstacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking.Models.TipoVehiculo", "TipoVehiculo")
                        .WithMany()
                        .HasForeignKey("TipoVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Estacionamiento");

                    b.Navigation("TipoVehiculo");
                });

            modelBuilder.Entity("Parkking.Models.Abono", b =>
                {
                    b.Navigation("AbonoVehiculos");

                    b.Navigation("Cuotas");

                    b.Navigation("Pagos");

                    b.Navigation("Plazas");
                });

            modelBuilder.Entity("Parkking.Models.AbonoPlaza", b =>
                {
                    b.Navigation("VehiculosFijos");
                });

            modelBuilder.Entity("Parkking.Models.Cliente", b =>
                {
                    b.Navigation("Abonos");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("Parkking.Models.Cochera", b =>
                {
                    b.Navigation("Plazas");
                });

            modelBuilder.Entity("Parkking.Models.Cuota", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("DetallesPago");
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.GrupoFinanciero", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("Reglas");
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.Movimiento", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("Parkking.Models.Finanzas.TipoGasto", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("Reglas");
                });

            modelBuilder.Entity("Parkking.Models.Pago", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Recibo");
                });

            modelBuilder.Entity("Parkking.Models.Seguridad.Usuario", b =>
                {
                    b.Navigation("Usuario_Estacionamiento");
                });

            modelBuilder.Entity("Parkking.Models.Vehiculo", b =>
                {
                    b.Navigation("AbonoVehiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
