// <auto-generated />
using System;
using Parkking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Parkking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EstacionamientoContext))]
    [Migration("20260319164401_movimientos-v2")]
    partial class movimientosv2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cochera", b =>
                {
                    b.Property<int>("CocheraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CocheraId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoriaCocheraId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoCochera")
                        .HasColumnType("integer");

                    b.Property<bool>("MultipleOcupacion")
                        .HasColumnType("boolean");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.HasKey("CocheraId");

                    b.HasIndex("CategoriaCocheraId");

                    b.HasIndex("EstacionamientoId");

                    b.ToTable("Cocheras");
                });

            modelBuilder.Entity("CocheraTipoVehiculo", b =>
                {
                    b.Property<int>("CocherasCocheraId")
                        .HasColumnType("integer");

                    b.Property<int>("VehiculosPermitidosTipoVehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("CocherasCocheraId", "VehiculosPermitidosTipoVehiculoId");

                    b.HasIndex("VehiculosPermitidosTipoVehiculoId");

                    b.ToTable("CocheraTipoVehiculo");
                });

            modelBuilder.Entity("MODELO.AbonoCochera", b =>
                {
                    b.Property<int>("AbonoCocheraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AbonoCocheraId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Cobrador")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CocheraId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("ModeloVehiculo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Patente")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("PrecioAcordado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoVehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("AbonoCocheraId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CocheraId");

                    b.HasIndex("TipoVehiculoId");

                    b.ToTable("AbonoCocheras");
                });

            modelBuilder.Entity("MODELO.TipoVehiculo", b =>
                {
                    b.Property<int>("TipoVehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoVehiculoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TipoVehiculoId");

                    b.HasIndex("EstacionamientoId");

                    b.ToTable("TiposVehiculo");
                });

            modelBuilder.Entity("Modelo_Ids.TarifaMensual", b =>
                {
                    b.Property<int>("TarifaMensualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TarifaMensualId"));

                    b.Property<int>("CategoriaCocheraId")
                        .HasColumnType("integer");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHoraActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoVehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("TarifaMensualId");

                    b.HasIndex("CategoriaCocheraId");

                    b.HasIndex("EstacionamientoId");

                    b.HasIndex("TipoVehiculoId");

                    b.ToTable("TarifasMensuales");
                });

            modelBuilder.Entity("MovimientoCaja", b =>
                {
                    b.Property<int>("MovimientoCajaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovimientoCajaId"));

                    b.Property<int?>("AbonoCocheraId")
                        .HasColumnType("integer");

                    b.Property<int>("CajaMensualId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PagoMensualId")
                        .HasColumnType("integer");

                    b.Property<string>("Responsable")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("TipoConcepto")
                        .HasColumnType("integer");

                    b.HasKey("MovimientoCajaId");

                    b.HasIndex("AbonoCocheraId");

                    b.HasIndex("CajaMensualId");

                    b.HasIndex("PagoMensualId");

                    b.ToTable("MovimientosCaja");
                });

            modelBuilder.Entity("PagoMensual", b =>
                {
                    b.Property<int>("PagoMensualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PagoMensualId"));

                    b.Property<int>("AbonoCocheraId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHoraCarga")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MercadoPagoId")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Mes")
                        .HasColumnType("date");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("Recargo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PagoMensualId");

                    b.HasIndex("AbonoCocheraId");

                    b.ToTable("PagosMensuales");
                });

            modelBuilder.Entity("Parkking_backend.Models.CajaMensual", b =>
                {
                    b.Property<int>("CajaMensualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CajaMensualId"));

                    b.Property<bool>("Cerrada")
                        .HasColumnType("boolean");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Mes")
                        .HasColumnType("date");

                    b.HasKey("CajaMensualId");

                    b.HasIndex("EstacionamientoId");

                    b.ToTable("CajasMensuales");
                });

            modelBuilder.Entity("Parkking_backend.Models.CategoriaCochera", b =>
                {
                    b.Property<int>("CategoriaCocheraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoriaCocheraId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoriaCocheraId");

                    b.HasIndex("EstacionamientoId");

                    b.ToTable("CategoriasCochera");
                });

            modelBuilder.Entity("Parkking_backend.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClienteId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("EstacionamientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ClienteId");

                    b.HasIndex("EstacionamientoId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Parkking_backend.Models.Estacionamiento", b =>
                {
                    b.Property<int>("EstacionamientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EstacionamientoId"));

                    b.Property<bool>("AplicaRecargo")
                        .HasColumnType("boolean");

                    b.Property<int>("DiaVencimientoAbono")
                        .HasColumnType("integer");

                    b.Property<int?>("DiasUmbralProporcional")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PorcentajeRecargo")
                        .HasColumnType("numeric");

                    b.HasKey("EstacionamientoId");

                    b.ToTable("Estacionamientos");
                });

            modelBuilder.Entity("Cochera", b =>
                {
                    b.HasOne("Parkking_backend.Models.CategoriaCochera", "CategoriaCochera")
                        .WithMany()
                        .HasForeignKey("CategoriaCocheraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking_backend.Models.Estacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaCochera");

                    b.Navigation("Estacionamiento");
                });

            modelBuilder.Entity("CocheraTipoVehiculo", b =>
                {
                    b.HasOne("Cochera", null)
                        .WithMany()
                        .HasForeignKey("CocherasCocheraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODELO.TipoVehiculo", null)
                        .WithMany()
                        .HasForeignKey("VehiculosPermitidosTipoVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MODELO.AbonoCochera", b =>
                {
                    b.HasOne("Parkking_backend.Models.Cliente", "Cliente")
                        .WithMany("Abonos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cochera", "Cochera")
                        .WithMany("Abonos")
                        .HasForeignKey("CocheraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODELO.TipoVehiculo", "TipoVehiculo")
                        .WithMany()
                        .HasForeignKey("TipoVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Cochera");

                    b.Navigation("TipoVehiculo");
                });

            modelBuilder.Entity("MODELO.TipoVehiculo", b =>
                {
                    b.HasOne("Parkking_backend.Models.Estacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamiento");
                });

            modelBuilder.Entity("Modelo_Ids.TarifaMensual", b =>
                {
                    b.HasOne("Parkking_backend.Models.CategoriaCochera", "CategoriaCochera")
                        .WithMany()
                        .HasForeignKey("CategoriaCocheraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parkking_backend.Models.Estacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODELO.TipoVehiculo", "TipoVehiculo")
                        .WithMany()
                        .HasForeignKey("TipoVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaCochera");

                    b.Navigation("Estacionamiento");

                    b.Navigation("TipoVehiculo");
                });

            modelBuilder.Entity("MovimientoCaja", b =>
                {
                    b.HasOne("MODELO.AbonoCochera", "Abono")
                        .WithMany()
                        .HasForeignKey("AbonoCocheraId");

                    b.HasOne("Parkking_backend.Models.CajaMensual", "CajaMensual")
                        .WithMany("Movimientos")
                        .HasForeignKey("CajaMensualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PagoMensual", "PagoMensual")
                        .WithMany("Movimientos")
                        .HasForeignKey("PagoMensualId");

                    b.Navigation("Abono");

                    b.Navigation("CajaMensual");

                    b.Navigation("PagoMensual");
                });

            modelBuilder.Entity("PagoMensual", b =>
                {
                    b.HasOne("MODELO.AbonoCochera", "AbonoCochera")
                        .WithMany("PagosMensuales")
                        .HasForeignKey("AbonoCocheraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbonoCochera");
                });

            modelBuilder.Entity("Parkking_backend.Models.CajaMensual", b =>
                {
                    b.HasOne("Parkking_backend.Models.Estacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamiento");
                });

            modelBuilder.Entity("Parkking_backend.Models.CategoriaCochera", b =>
                {
                    b.HasOne("Parkking_backend.Models.Estacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamiento");
                });

            modelBuilder.Entity("Parkking_backend.Models.Cliente", b =>
                {
                    b.HasOne("Parkking_backend.Models.Estacionamiento", "Estacionamiento")
                        .WithMany()
                        .HasForeignKey("EstacionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacionamiento");
                });

            modelBuilder.Entity("Cochera", b =>
                {
                    b.Navigation("Abonos");
                });

            modelBuilder.Entity("MODELO.AbonoCochera", b =>
                {
                    b.Navigation("PagosMensuales");
                });

            modelBuilder.Entity("PagoMensual", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Parkking_backend.Models.CajaMensual", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Parkking_backend.Models.Cliente", b =>
                {
                    b.Navigation("Abonos");
                });
#pragma warning restore 612, 618
        }
    }
}
